[package]
name = "visuals"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
softbuffer = "=0.4.6"
winit = "0.30.11"
plotters = "0.3.7"
integrator = { version = "0.1.0", path = "../integrator" }
rand = "0.9.2"

[lints.rust]
unused = "allow"